### ISSUE TITLE
where can I download taxcheck?

### ISSUE THREAD

**Issue by zckoo007** [EBI-Metagenomics/genomes-pipeline#3]
Hi 

Thank you for sharing the code

where can I download taxcheck.sh ？
Does taxcheck a software?
I search all the github and google but can't find it

**Comment by alexmsalmeida** [comment]
Hi,

The taxcheck.sh is just a custom script making use of the Contig Annotation Tool (CAT) to infer taxonomic consistency of contigs. We did not end up using it for our paper, but are providing it just in case someone finds it useful. You can find it in the custom_scripts/ directory of this repo.

Alex
