### ISSUE TITLE
Question about lowercase/uppercase genomes

### ISSUE THREAD

**Issue by franciscozorrilla** [EBI-Metagenomics/genomes-pipeline#33]
Hi, I noticed that some genome `.fna` files e.g. [MGYG000002322](https://www.ebi.ac.uk/metagenomics/genomes/MGYG000002322#genome-browser) are all lowercase, while others are all uppercase [MGYG000000001](https://www.ebi.ac.uk/metagenomics/genomes/MGYG000000001#genome-browser). Could you explain what the significance of the lower/upper case genomes is?

Best,
Francisco

**Comment by tgurbich** [comment]
Hi Francisco,

The lowercase doesn't have significance here, the genomes were obtained from different sources and some were formatted this way.

Best,
Tanya

**Comment by franciscozorrilla** [comment]
Thanks for the clarification, just wanted to make sure I wasn't missing something there :) 

Best,
Francisco
