### ISSUE TITLE
Mash file for singletons

### ISSUE THREAD

**Issue by KeteSakharova** [EBI-Metagenomics/genomes-pipeline#37]
If catalogue consists only of singletons there will be no _mash.tsv_ file. That means it should be optional and that fact should be counted in the following pipeline
https://github.com/EBI-Metagenomics/genomes-pipeline/blob/dev/modules/split_drep.nf#L30

**Comment by mberacochea** [comment]
Moved to https://www.ebi.ac.uk/panda/jira/browse/EMG-4407
