### ISSUE TITLE
Improve metadata script

### ISSUE THREAD

**Issue by KeteSakharova** [EBI-Metagenomics/genomes-pipeline#38]
Metadata script does a lot of ENA API calls to get information for each genome. If ENA API is unstable - whole script fails -> pipeline fails. -resume function runs everything from scratch.
Maybe it makes sense to improve this script:
- create a backup file for already fetched metadata
- fetch as one big file and parse it
- fetch metadata in the start of pipeline (in parallel with fetch ...)

**Comment by mberacochea** [comment]
Moved to -> https://www.ebi.ac.uk/panda/jira/browse/EMG-4408
