### ISSUE TITLE
dead links

### ISSUE THREAD

**Issue by QingDAI0225** [EBI-Metagenomics/genomes-pipeline#73]
https://github.com/EBI-Metagenomics/genomes-pipeline/blob/ac2e8f1be5c8f6d31ea56abd266c528be7ccabbf/README.md?plain=1#L78

These links don't work:

([fetch_ena.py](https://github.com/EBI-Metagenomics/genomes-pipeline/blob/master/containers/genomes-catalog-update/scripts/fetch_ena.py)) 

and 

([fetch_ncbi.py](https://github.com/EBI-Metagenomics/genomes-pipeline/blob/master/containers/genomes-catalog-update/scripts/fetch_ncbi.py))

**Comment by KateSakharova** [comment]
Hello @QingDAI0225,

Thank you for raising it! 
All scripts are available in https://github.com/EBI-Metagenomics/genomes-pipeline/blob/master/bin/
and links are fixed in PR #75 

Best,
Kate

**Comment by KateSakharova** [comment]
Done!
