### ISSUE TITLE
Missing EBI profile

### ISSUE THREAD

**Issue by amardeepranu** [EBI-Metagenomics/genomes-pipeline#81]
https://github.com/EBI-Metagenomics/genomes-pipeline/blob/853487f6dda1420fd8b6b41dd4aff5c8540c7e37/nextflow.config#L27

I can't seem to find the ebi profile in nextflow.config that's referenced in the README and above

**Comment by KateSakharova** [comment]
Hi @amardeepranu, 
_ebi profile_ is a general term. You can check **codon_lsf** or **codon_slurm**  profiles. Databases are described [here](https://github.com/EBI-Metagenomics/genomes-pipeline/tree/master?tab=readme-ov-file#reference-databases).
