### ISSUE TITLE
SanntiS floods CPUs

### ISSUE THREAD

**Issue by lam-c** [EBI-Metagenomics/genomes-pipeline#85]
Hi, developers

I got a warning on CPU usage on process:SANNTIS, which flooding CPUs regardless the process cpu (1) assigned in config.

I checked the scripts and found that execution command of sanntis lacking `cpu` params. I did some modification like this and reran this step. 

![image](https://github.com/EBI-Metagenomics/genomes-pipeline/assets/38537368/1618fa48-51c7-470a-8757-15750093c72e)

However, The cpus still ran out of limits. I reported this issue to Sanntis too https://github.com/Finn-Lab/SanntiS/issues/6, but not quite sure how to fix it. I wonder if there any options we could skip Sanntis temporarily?

---

Environment:

```
System: Red Hat 8.5.0-10
Singularity-ce: version 3.10.2-1.el8
Linux Cgroups v1  # thus cannot limit cpus when creating container
Nextflow: version 23.10.0 build 5889
Container: "quay.io/microbiome-informatics/sanntis:0.9.3.2"
```

Execution scripts and log files:
[logfiles.zip](https://github.com/EBI-Metagenomics/genomes-pipeline/files/13898745/logfiles.zip)

**Comment by mberacochea** [comment]
Hey,

@lam-c thanks for the bug report. The PR #86 adds the `--cpu` flag but doesn't fix the underlying issue with SanntiS. I'll close this one when https://github.com/Finn-Lab/SanntiS/issues/6 is fixed

Cheers
